### ISSUE TITLE
the transaction payload input are not addresses but trx ids, which do not map to the current transaction

### ISSUE THREAD

**Issue by ashisherc** [KtorZ/cardano-ogmios#1]
#### What Git revision are you using? 
git version 2.16.3
#### What operating system are you using, and which version?

- Ubuntu 18.04

#### Describe what the problem is? 
The block when has transactions in it, the transaction payload has 2 fields, input and output.

While the output object has address with value (ADA amount), the input does not seem to have input addresses, it has trx ids, which do not map to the current transaction in any way

#### What should be the expected behavior?
The input object should have input addresses

The Block object is here
```
{
  "body": {
    "updatePayload": {
      "votes": [],
      "proposal": null
    },
    "txPayload": [
      {
        "tx": {
          "inputs": [
            **{
              "index": 9,
              "txId": "2341938113f607a28791a0205bb9c11668cf8c049389b46448a35fd6d9479252"
            },
            {
              "index": 0,
              "txId": "f20f922e6d91b7b36de57a454fcd2da24a0e6f0b66bcb5754fc0ddfeaf270935"
            },
            {
              "index": 1,
              "txId": "0ddeacff2fb06cc461966ad61909e695281064e181aecaf0afcf0feb4af2d16d"
            }**
          ],
          "outputs": [
            {
              "value": 179943821867,
              "address": "DdzFFzCqrht12283jGHdtiMQzvzyUXbmZmLwaMS86mNSMLhny3yjoA1jzZySoyTAn5GYw24DhkLnSMNuME3DQv6mcwHa2tJEVug3vKji"
            },
            {
              "value": 11594380000,
              "address": "DdzFFzCqrht6MR4ha7efZgjVFM2sMGdEmKMcrfaHL7RspMq2JUPv6rs5J843P5eXYS7Dh6vmjqNr7SHDv8RkrYUwWxfwxdAqjy7gGPdE"
            },
            {
              "value": 18322080000,
              "address": "DdzFFzCqrht6MR4ha7efZgjVFM2sMGdEmKMcrfaHL7RspMq2JUPv6rs5J843P5eXYS7Dh6vmjqNr7SHDv8RkrYUwWxfwxdAqjy7gGPdE"
            },
            {
              "value": 178451271473,
              "address": "DdzFFzCqrhsvmVNoCTbijeAhv8xa2HLnV5dfiqa2faQmH6UnMfZQV9wv6Mz86wTQQrvYB1GxoHLH3JzwpfaedLycuR89jEn2xgAynwet"
            }
          ]
        },
        "witness": [
          {
            "witnessVK": {
              "signature": "d2785d1f5bceb651b76cf3b261360a4fe519a16ce48f62d6346d8e07010e1ac9296df81d80563ebf67a50357524a8578052320498cf5d1fe339891cda8c7e30d",
              "key": "QW3A+BXSBuzvNnX2BcYjE4FZLpODqEKJSbSI7slWTHuwICElOmvwHIUmUnUfPTYuAChYjKAL1WyrWB9Zcbux7A=="
            }
          },
          {
            "witnessVK": {
              "signature": "5149a05415fca7a6554fe5b41f30fed87c21486d0609ed681f6b62589c3a77226918921499376dfaf2041cb87666104115ec788dbb70995e456318f6e657cf0e",
              "key": "I5zqryP8GhAooy5YaqJ+2+NjRUSjlWZ4BP4Ss+8dakMRX6TUsMT+iX+rLiglGO4OJ95lEvRk4ccSohrdRQe6mA=="
            }
          },
          {
            "witnessVK": {
              "signature": "bb9e8a8d6d266dc8ace96f4c8928327e854611327dddd2518c57bb705125c514e1fdf44ba815eecd414c089205057c14a175b223bdeb5557fd01b53f22be8506",
              "key": "0REmxKwPzoB1TwzOvigwMnf1Jq1fv941CInwa9eb89gTNmgJOYBTJLi9xDCYGxwxHKIeEfkWLEM0VDX0JUrxwQ=="
            }
          }
        ]
      }
    ],
    "dlgPayload": []
  },
  "header": {
    "signature": {
      "signature": "3ac739ca6f61d38061fb5704db746923fbc9ca3fa4f556aef938305285b0d27cba7e05bfbb4624718078930417360d03b207572974c732a7616ce55460ebd80c",
      "dlgCertificate": {
        "signature": "e03e62f083df5576360e60a32e22bbb07b3c8df4fcab8079f1d6f61af3954d242ba8a06516c395939f24096f3df14e103a7d9c2b80a68a9363cf1f27c7a4e307",
        "delegateVK": "YSYalbdhPua/IGfa13twNJcpsMUNV7wc8w3g20oec6iF0AVK98I/xsN5GdukHGAqV+LQ+TKaeVS4ZzONb7LJRQ==",
        "issuerVK": "G8l6L+AsKXiAzo7P2Zf+TB7AnuEP7u6faGdgFmsFKB1ig0aP/ZO+ywyVbM3dZC35sSRMkVkRGF+kk1X28iv6uQ==",
        "epoch": 0
      }
    },
    "proof": {
      "utxo": {
        "root": "ea0bd049bf8205c0faada11ebb7f3c5ee393209b00409f7678ed43c5aec0739b",
        "witnessesHash": "824289abfa6491fa749a1cb974f741d39d2c258638fd85f096d1e42e7c6d7f01",
        "number": 1
      },
      "delegation": "afc0da64183bf2664f3d4eec7238d524ba607faeeab24fc100eb861dba69971b",
      "update": "4e66280cd94d591072349bec0a3090a53aa945562efb6d08d56e53654b0e4098"
    },
    "protocolVersion": {
      "minor": 0,
      "major": 1,
      "patch": 0
    },
    "genesisKey": "G8l6L+AsKXiAzo7P2Zf+TB7AnuEP7u6faGdgFmsFKB1ig0aP/ZO+ywyVbM3dZC35sSRMkVkRGF+kk1X28iv6uQ==",
    "protocolMagicId": 764824073,
    "slot": 4053832,
    "softwareVersion": {
      "appName": "cardano-sl",
      "number": 2
    },
    "prevHash": "c2b93abc6a83033b09b52e82f3d06baf404746a63d943856cf42f16ed049aea1",
    "blockHeight": 4051730
  }
}
```

**Comment by KtorZ** [comment]
Hey! Thanks for your question! 
I am afraid this is actually expected. Ogmios will return data as they exists on-chain / are returned by core nodes. It doesn't do any aggregation or post-treatment apart from converting them from raw binary to JSON.

Inputs of a transaction are indeed a pair of a **previous transaction id**, and an output index in that transaction. Said differently, an input is an output of a previous transaction, also called an _Unspent Transaction Output (UTxO). 
The main reason for this is because an address does not uniquely identify an input. Imagine the scenario where txA and txB both send funds to an address ADDR. In practice, their exists two inputs at ADDR, but no way to reference them by using just ADDR. UTxOs don't automatically merge like you would expect in a more common accounting style distribution. In an account, making two money transfers to the same account number would increase the balance of the account; true. But UTxOs are much more like bank notes and coins. If someone gives you two 10EUR bills, you don't end up with one 20EUR bill in your wallet. Same goes for UTxO and explains why they are identified by the transaction by which they were issued (and not the address they refer to). 

See also: https://github.com/input-output-hk/cardano-wallet/wiki/About-UTxO

**Comment by ashisherc** [comment]
Hey KtorZ, thank you for the detailed response, my bad. I will have a look at this specification.
Also, I wanted to know if you are going to support this project in the long run or a similar project will be supported by IOHK?

**Comment by KtorZ** [comment]
I'll upgrade the project to support the new Shelley blockchain data-types in the upcoming days and may add in the future any new mini-protocol that the networking team may develop.

I have plans to use Ogmios for another personal project in the future, and I'll be happy to discuss improvements or bug fixes with the community :)

**Comment by ashisherc** [comment]
Okay, that is awesome. Thank you!! I will be happy to submit any new bugs or features I may find. I will close this issue. :)
