### ISSUE TITLE
QueryResponse[ledgerTip] type. Should this be Tip instead of Point?

### ISSUE THREAD

**Issue by rhyslbw** [KtorZ/cardano-ogmios#11]
``` json
{ "oneOf":
          [ { "$ref": "#/definitions/Point" }
          , { "$ref": "#/definitions/EraMismatch" }
          , { "$ref": "#/definitions/QueryUnavailableInCurrentEra" }
          ]
        }
```
https://github.com/KtorZ/cardano-ogmios/blob/master/docs/static/ogmios.wsp.json#L577

**Comment by KtorZ** [comment]
I agree, but it's beyond me here :no_mouth: 

https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Ledger/Query.hs#L83

This :point_up: is how the `ouroboros-network` defines it, as a `Point` :/
