### ISSUE TITLE
Where is the dashboard served?

### ISSUE THREAD

**Issue by rhyslbw** [KtorZ/cardano-ogmios#12]
3.0.0 Release notes mentions:
> Interactive dashboard leveraging Ogmios health's endpoint and local state query protocol to show metrics in real-time.

Looking at [the code](https://github.com/KtorZ/cardano-ogmios/blob/bb62010c10fa7703b95c846b7aaacc4c8e2796c5/ogmios-server/src/Ogmios/App/Server.hs#L79) it should be at the root, however I'm just seeing the previous page:

![image](https://user-images.githubusercontent.com/303881/110324935-c5e5ea00-806a-11eb-9c47-c317303efafe.png)

**Comment by rhyslbw** [comment]
Ok, that's odd. I rebuilt the images from source, and I'm now getting the dashboard at the root. Either I had an issue with the Docker images, or I didn't hard refresh the browser cachge.

Either way, great improvement!

**Comment by KtorZ** [comment]
I imagine it's an issue with the browser cache indeed :thinking:. There's a link to the dashboard from the logs, but I realize it's not mentioned anywhere in the user manual (and same goes for the available runtime metrics and the health endpoint).
