### ISSUE TITLE
Reflection responses keyed as mirror in wsp.json

### ISSUE THREAD

**Issue by rhyslbw** [KtorZ/cardano-ogmios#19]
#### What Git revision are you using? 
`0790ce4e98e6250f68f3c6903b1ad0ae9ca91d65`

#### What operating system are you using, and which version?

- [x] Linux / Ubuntu

#### Describe what the problem is? 
There's a couple of `reflection` objects keyed as `mirror`:

##### AcquireResponse
https://github.com/KtorZ/cardano-ogmios/blob/0790ce4e98e6250f68f3c6903b1ad0ae9ca91d65/docs/static/ogmios.wsp.json#L376 

##### ReleaseResponse
https://github.com/KtorZ/cardano-ogmios/blob/0790ce4e98e6250f68f3c6903b1ad0ae9ca91d65/docs/static/ogmios.wsp.json#L438

#### What should be the expected behavior?
Should be `reflection`

**Comment by KtorZ** [comment]
Nice catch. The test generator now make sure to also generate responses with non-null reflection. Fixed in   86e6f1457f3ace6cab310931de33816e1db9c9c7
