### ISSUE TITLE
Unable to sync blocks from genesis or a jump point

### ISSUE THREAD

**Issue by ashisherc** [KtorZ/cardano-ogmios#2]
#### What Git revision are you using? 
git version 2.16.3
#### What operating system are you using, and which version?
Ubuntu 18.04

#### Describe what the problem is? 
1. I wanted to sync blocks from a given point by intersecting at it and requesting NEXT, but it sends rollBackward message and starts sending blocks from the tip.

2. I then tried to sync blocks from genesis, left the INIT as it is in the demo.js and changed the INIT case, instead of jumping to tip, I changed it to request NEXT

#### What should be the expected behavior?
I should receive blocks starting from the intersection, eg. the cursor

### code I am trying

```
socket.onopen = function (event) {
    socket.wsp("FindIntersect", { points: ["origin"] }, { step: "INIT" });
};

socket.onmessage = function (event) {
  const msg = JSON.parse(event.data);
  switch (msg.reflection.step) {

    case "INIT":
        socket.wsp("RequestNext", {}, { step: "NEXT" });
        break;

    case "JUMP":
      if (msg.result.IntersectionNotFound) {
        const { slot, hash } = msg.result.IntersectionNotFound.tip
        socket.wsp("FindIntersect", { points: [ { slot, hash } ] }, { step: "JUMP" });
      } else {
        socket.wsp("RequestNext", {}, { step: "NEXT" });
      }
      break;

    case "NEXT":
      console.log(msg.result);
      socket.wsp("RequestNext", {}, { step: "NEXT" });
      break;
  }
};

socket.onclose = function (event) {
  console.log("Connection closed.");
};
```

### Output

```
{ RollBackward:
   { point: 'origin',
     tip:
      { hash:
         '57bc62c63ea75d41bbdc73391a078c820f51c53f747ee437d0f5c421f5bb73b2',
        blockNo: 4069863,
        slot: 4071965 } } }
{ RollForward:
   { block: { header: [Object] },
     tip:
      { hash:
         '57bc62c63ea75d41bbdc73391a078c820f51c53f747ee437d0f5c421f5bb73b2',
        blockNo: 4069863,
        slot: 4071965 } } }
{ RollForward:
   { block: { body: [Object], header: [Object] },
     tip:
      { hash:
         '57bc62c63ea75d41bbdc73391a078c820f51c53f747ee437d0f5c421f5bb73b2',
        blockNo: 4069863,
        slot: 4071965 } } }
{ RollForward:
   { block: { body: [Object], header: [Object] },
     tip:
      { hash:
         '57bc62c63ea75d41bbdc73391a078c820f51c53f747ee437d0f5c421f5bb73b2',
        blockNo: 4069863,
        slot: 4071965 } } }
```

Also notice one more thing, after rollBackward, rollForward is received duplicated, again and again, a duplicate block. The code above is as it is. I can confirm no duplicate console log

**Comment by KtorZ** [comment]
Hey @ashisherc, there's a discrepancy between your explanation of _what the code should do_ and, from the code above actually does ^.^

Let me clarify.  Here's what's happening with the code you've written:

1. When the connection is open, you ask the node to find an intersection with [Origin]. This is guaranteed to succeed and resolve to `Origin`

2. Regardless of whether an intersection has been found or not, you ask for the next block. 

> :information_source: Upon successfully finding an intersection, the node **always** starts by demanding the client to roll back to the intersection point

3. The node replies with a `RollBackward` to Origin. And you request next block again.

4. The node replies with Origin+1. And you request next block again... an so forth. 

So your code is effectively synchronizing from genesis.

**Comment by ashisherc** [comment]
Yes, but when I request the next block, I am receiving not the next block but the block at the tip, please have a look at the console log, am I missing anything?

**Comment by ashisherc** [comment]
Not sure, what is going on. Instead of getting origin+1, I am just getting the same block again and again by requesting NEXT, I tried it just now and I am getting below output.

```
{ RollBackward:
   { point: 'origin',
     tip:
      { hash:
         'a9b4ac5abe18e44b7be60d9938a51c45bba0b7c9892a6f41d8b2eedf1dba39d1',
        blockNo: 4070819,
        slot: 4072921 } } }
{ RollForward:
   { block: { header: [Object] },
     tip:
      { hash:
         'a9b4ac5abe18e44b7be60d9938a51c45bba0b7c9892a6f41d8b2eedf1dba39d1',
        blockNo: 4070819,
        slot: 4072921 } } }
{ RollForward:
   { block: { body: [Object], header: [Object] },
     tip:
      { hash:
         'a9b4ac5abe18e44b7be60d9938a51c45bba0b7c9892a6f41d8b2eedf1dba39d1',
        blockNo: 4070819,
        slot: 4072921 } } }
{ RollForward:
   { block: { body: [Object], header: [Object] },
     tip:
      { hash:
         'a9b4ac5abe18e44b7be60d9938a51c45bba0b7c9892a6f41d8b2eedf1dba39d1',
        blockNo: 4070819,
        slot: 4072921 } } }
{ RollForward:
   { block: { body: [Object], header: [Object] },
     tip:
      { hash:
         'a9b4ac5abe18e44b7be60d9938a51c45bba0b7c9892a6f41d8b2eedf1dba39d1',
        blockNo: 4070819,
        slot: 4072921 } } }
{ RollForward:
   { block: { body: [Object], header: [Object] },
     tip:
      { hash:
         'a9b4ac5abe18e44b7be60d9938a51c45bba0b7c9892a6f41d8b2eedf1dba39d1',
        blockNo: 4070819,
        slot: 4072921 } } }
```

**Comment by ashisherc** [comment]
All that needed was coffee.
