### ISSUE TITLE
Enhance metrics with "network synchronization" 

### ISSUE THREAD

**Issue by KtorZ** [KtorZ/cardano-ogmios#25]
#### Describe your idea, in simple words.

Ogmios performs well when connected to a fully synced node. Before running any computationally expensive tasks (e.g. chain-sync), it's best to wait for the underlying node to be fully synchronized with the network. The node however doesn't report such information in logs, but only report an absolute slot number. 

Ogmios could on start-up, query the era start from the node, the genesis parameters of the current era, and then, calculate what the network tip should be. From there, it should be able to calculate how far its underlying node is from the network tip and provide a useful "network synchronization" metric as a percentage. 

#### Why is it a good idea?

- I often find it useful to know where is my underlying node, in particular to know whether running benchmarks on Ogmios makes sense or whether I should wait for the node to be synchronized. 

- Since this information is quite hard to extract from the node but useful also to monitor the network connectivity of the node, it's useful to use Ogmios as a proxy to retrieve this interesting metric.

#### Are you willing to work on it yourself?

:+1:

**Comment by rhyslbw** [comment]
:100:
