### ISSUE TITLE
Provide support for custom network: Guild network

### ISSUE THREAD

**Issue by MarcelKlammer** [KtorZ/cardano-ogmios#35]
Could you please add the guild network. It has 1h epochs, which is better suited for quick tests.

```
...
Just "guild" -> do
            pure guildNetworkParameters
...
-- Hard-coded guild network parameters
guildNetworkParameters
    :: NetworkParameters
guildNetworkParameters =
    NetworkParameters
        { networkMagic = NetworkMagic 141
        , slotsPerEpoch = 3600
        , systemStart = SystemStart $ posixSecondsToUTCTime 1612317107
        }
```

**Comment by MarcelKlammer** [comment]
Ah, yeah. It might just be?

```
OGMIOS_NETWORK="141: 1612317107"
```

**Comment by KtorZ** [comment]
Ho! It is already possible to specify a custom network as value for the environment variable (this is detailed in the command-line --help, for example: OGMIOS_NETWORK=141:1612317107)

The Epoch slot is however not configurable, but this could be changed.

**Comment by MarcelKlammer** [comment]
Yeah, it would be nice to have guild support, so making that epochLength parameter configurable would be nice :)

**Comment by KtorZ** [comment]
I agree. The OGMIOS_NETWORK env var will accept an extra value for the slots per epoch / epoch length. I'll also give an explicit example in the cli --help using the parameters of the guild network if you don't mind.

**Comment by MarcelKlammer** [comment]
I don't represent the guild in any way. I will point someone from them here to give permission or deny.

**Comment by Scitz0** [comment]
> I agree. The OGMIOS_NETWORK env var will accept an extra value for the slots per epoch / epoch length. I'll also give an explicit example in the cli --help using the parameters of the guild network if you don't mind.

Hi, feel free to add guild example 👍

**Comment by KtorZ** [comment]
@MarcelKlammer I renamed the issue to be more easily searchable in the future and added appropriate labels.

**Comment by MarcelKlammer** [comment]
Thanks to the image ogmios is super easy to integrate into existing cardano-graphql setups. Matter of minutes.

I would love to see that change in the 3.2.0 release to complete our setup :).

Will start testing it now.

Please consider a Telegram group for talking about ogmios stuff.

**Comment by KtorZ** [comment]
> I would love to see that change in the 3.2.0 release to complete our setup :).

Consider it done :wink: 

> Please consider a Telegram group for talking about ogmios stuff.

Genuine question: what would be the added benefits compared to Github issues + user manual? I am a little bit scared of ad-hoc conversations which provide value but fail to be captured in a more permanent way.

**Comment by MarcelKlammer** [comment]
Well I guess I'm trained to reach out to like minded Cardano devs on specific questions in specific Telegram channels. But since I have contact to most of the hand on guys, it won't matter.

Either way is fine I guess. :)
