### ISSUE TITLE
ogmios.wsp.json - Acquire - args - point

### ISSUE THREAD

**Issue by MarcelKlammer** [KtorZ/cardano-ogmios#39]
args 

points 

should be 

point

**Comment by rhyslbw** [comment]
Hi Marcel,

We'll be happy to look into this if you can elaborate and include code links. This is the JSON-WSP schema:

https://github.com/KtorZ/cardano-ogmios/blob/47ac39dbbaf2869d27ba09e9361bab593775f0ff/docs/static/ogmios.wsp.json#L292-L326

**Comment by MarcelKlammer** [comment]
```
, "properties": 
         { "points": { "$ref": "#/definitions/Point" } 
         } 
       } 
```

should be

```
, "properties": 
         { "point": { "$ref": "#/definitions/Point" } 
         } 
       } 
```

**Comment by KtorZ** [comment]
Yes indeed. I need to find a good way to generically test the **request** schemas against the actual implementation. Most of the code used for testing the responses should be reusable for that purpose.
